### ISSUE TITLE
Remove cookie in browser when signing out

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-query-client#40]
ref https://github.com/graasp/graasp-feedback/issues/10

**Comment by juancarlosfarah** [comment]
I'm still viewing this behaviour. @Julien-Torrent, can you try to reproduce?

**Comment by Julien-Torrent** [comment]
@juancarlosfarah, @pyphilia This is still present in the dev version.

The user is redirected to login page before the cookie is deleted.

I'm gonna try to fix it
